### PR TITLE
[WIP] Sphinx documentation

### PR DESCRIPTION
**Pull request by ondrowan**
Things didn't go as planned, so I'm opening at least WIP pull request with todo list. Feel free to review the bits I've done so far. I'm not a native english speaker, so there might be some grammar mistakes.

Todo:

- [x] Document `assets` and `asset_items`
- [x] Document `localization` module
- [x] Document `remote_storage` module
- [x] Document `sim` module
- [x] Document `user` module
- [x] Find out how to set the theme for readthedocs
- [x] Figure out better way to organize menu (endpoint wrappers should be grouped together)
- [x] Remove `API reference` since most of it will be covered in separate sections
- [x] Remove `code-block` blocks (as they are not needed for python shell examples)
- [x] Readme should contain only essential information and link to docs
- [ ] Squash commits

### CODE REVIEW

**Comment by ondrowan** [comment]
Does `GetUGCFileDetails` method work right now? I haven't used it anywhere before and it seems to return code 9 for every item (or at least Dota 2 items I've tried). I suspect it might have something to do with recent outrage regarding paid mods as Workshop seems to be down at the moment as well.

**Comment by Lagg** [comment]
Sorry for late response. I've been more or less out of town and might be for a little longer. Let me know when your stuff is complete and I'll merge when I'm back. As far as GetUGCFileDetails it would seem that the testcases are passing. So it's at least working for semi-old stuff. Hard to tell these days if it's just standard Valve downtime or an actual bug (though arguably it's a bug in the first place, but meh. One thing at a time)

**Comment by ondrowan** [comment]
I have finally finished "good enough" version of the docs. It'd be great if you built it locally and gave me some feedback. There are also few unfinished things you could maybe help me with:

* Some methods aren't properly documented (besides examples). It possibly isn't a big deal. We can finish them later.
* Remote Storage class lacks example as I couldn't figure how to use it. It'd be cool if you helped me with this one.
* Class docs are combination of class docstrings and custom docs I wrote. Constructor docstrings aren't taken into consideration at all. AFAIK Sphinx allows to take docstrings from both class and constructor, but it is possible to turn it on _only_ globally. I'm not sure what would be the appropriate way to handle this. We can either document everything on docstring level (examples as well) and use only those or take, for example, class docstrings only and add custom docs (which I do now). Any thoughts?

**Comment by Lagg** [comment]
Alright, will take a look when I get back (again apologies for late response) for the moment though no I wouldn't be too worried about completeness. Better a first draft than none at all.

Remote storage is basically what the vanity_url stuff is to user profiles. You pass it a 64 bit UGC ID and it'll fetch metadata for the file matching that ID like a URL to it and its filesize. One place this is used is decals for TF2. You get a UGC ID and then turn that into a usable URL. [Here's](http://git.optf2.com/optf2/tree/optf2/models.py#n312) a relevant snippet from optf2.

As for the ctor docstrings I think it might look weird seeing two docstrings not intended to be read together are concatenated in the doc. I myself just leave it at the default of class since that's the string usually giving the overview anyway.

**Comment by Lagg** [comment]
Okay had a chance to do an initial lookover and I'm really liking it so far. I added [this](http://steamodd.readthedocs.org) and [this](https://github.com/Lagg/steamodd/tree/sphinx-docs) (which also contains a fix for what looked like a typo).

Besides the typo at the moment the only other problem I saw was that you didn't put your name in the copyright line in conf.py. I like to make sure people are properly attributed so I fixed that as well.

**Comment by Lagg** [comment]
Also added some initial documentation for remote_storage.

**Comment by Lagg** [comment]
and also fixed my silly mistake with remote_storage's docs. I think at this point it's pretty close to merge-ready. I haven't really did any proper proofread of your stuff but honestly for a non-native speakers it's pretty high quality so I don't imagine any issues and if there are they're easily fixed.

Let me know if you agree and I'll do the merge (unless you think it's not ready or needs more done of course). Afterwards I'm going to be pushing a new release to pypi. Should I merge my branch or did you want to rebase your stuff on it and push so I can use github's web UI to do it?

**Comment by ondrowan** [comment]
I have squashed couple of commits together, added docs for new method from #39 and rebased master onto sphinx branch (and force pushed... twice, so sorry for extra noise in PR feed). I think it's in "good enough" state for now and can be merged into master. We can polish it more later on.

:ship: :it: \o/

**Comment by Lagg** [comment]
Great, thanks. Will probably push 4.19 to pypi later on.

**Pull request merged**
